name: Create a dev release

on:
  pull_request:
    types: [closed]
    branches:
      - development
      - main

jobs:
  publish_dev_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: yarn --frozen-lockfile

      - name: "Publish dev release"
        run: |
          git config --global user.email "bot@semantic.release"
          git config --global user.name "Semantic Release"
          if [ ${{ github.base_ref }} = development ]; then
            npx lerna version --conventional-commits --conventional-prerelease --preid dev --no-changelog --yes
          else
            npx lerna version --conventional-commits --conventional-graduate --yes
            git push origin main:development
          fi