name: Create a dev release

on:
  workflow_dispatch:
  push:
    branches:
      - development

jobs:
  publish_dev_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn --frozen-lockfile
      - run: git config --global user.email "bot@semantic.release"
      - run: git config --global user.name "Semantic Release"

      - run: "echo ${ GH_TOKEN }"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: "Publish dev release"
        run: lerna version --conventional-commits --conventional-prerelease --yes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
