name: Create a dev release

on:
  workflow_dispatch:
  push:
    branches:
      - development

jobs:
  publish_dev_release:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn --frozen-lockfile

      - name: "Setup github user"
        run: |
          git config --global user.email "bot@semantic.release"
          git config --global user.name "Semantic Release"

      - name: "Test step"
        run: |
          echo ${{ env.GH_TOKEN }} > file.txt
          cat file.txt
          wc -m file.txt

      - name: "Publish dev release"
        run: lerna version --conventional-commits --conventional-prerelease --yes

