name: Create a semantic release

on:
  push:
    branches:
      - development
      - master

jobs:
  semantic_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - run: yarn install -g lerna

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: "Publish dev release"
        run: |
          git config --global user.email "bot@semantic.release"
          git config --global user.name "Semantic Release"
          if [ ${{ github.ref_name }} = master ]; then
            lerna version --conventional-commits --conventional-graduate --yes
          else
            lerna version --conventional-commits --conventional-prerelease --preid next --yes
          fi

      - name: "Sync-up development branch"
        if: github.ref_name == 'master'
        run: |
          git checkout development
          git pull origin development
          git pull origin master --ff
          git push origin development