name: Create a semantic release

on:
  push:
    branches:
      - development
      - master

jobs:
  semantic_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - run: yarn global add lerna

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: "Setup git user"
        run: |
          git config --global user.email "bot@semantic.release"
          git config --global user.name "Semantic Release"

      - name: "Create dev release"
        if: github.ref_name == 'development'
        run: |
          lerna version --conventional-commits --conventional-prerelease --preid next --yes --no-push
          git push origin development
          node devops/publish-tags.js

      - name: "Create stable release"
        if: github.ref_name == 'master'
        run: |
          lerna version --conventional-commits --conventional-graduate --yes --no-push
          git push origin master
          node devops/publish-tags.js
#         # Synchronise the development branch with the master branch
          git checkout development
          git pull origin development
          git pull origin master --ff
          git push origin development